[config]
schemaVersion = "0.0.1"

[package]
namespace = "xhayper"
name = "RichPresenceAPI"
versionNumber = "1.0.0"
description = "'discord-rpc-csharp' for BepInEx plugin"
websiteUrl = "https://github.com/xhayper/RichPresenceAPI"
containsNsfwContent = false

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "bin/Release/RichPresenceAPI/RichPresenceAPI.dll"
target = "plugins/io.github.xhayper.RichPresenceAPI/RichPresenceAPI.dll"

[[build.copy]]
source = "bin/Release/RichPresenceAPI/discord-rpc-unity.dll"
target = "plugins/io.github.xhayper.RichPresenceAPI/discord-rpc-unity.dll"

[[build.copy]]
source = "bin/Release/RichPresenceAPI/DiscordRPC.dll"
target = "plugins/io.github.xhayper.RichPresenceAPI/DiscordRPC.dll"

[[build.copy]]
source = "Assets"
target = "plugins/io.github.xhayper.RichPresenceAPI/Assets"

[publish]
categories = ["libraries"]
